# Generated by Django 4.2.4 on 2023-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mess',
            name='name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='mess_admin',
            name='name',
            field=models.CharField(default='N/A', max_length=30, unique=True),
        ),
    ]
