# Generated by Django 4.2.4 on 2023-10-30 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_mess_name_alter_mess_admin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.mess'),
        ),
    ]
