# Generated by Django 4.2.4 on 2023-10-30 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_mess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mess_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bazar_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('note', models.CharField(max_length=1000, null=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BazarEntry',
        ),
    ]
